name: hot_deals_hungary
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1
  google_fonts: ^3.0.1
  get: ^4.6.5
  badges: ^2.0.3
  sqflite:
  path:
  intl: ^0.17.0
  #firebase_auth: ^3.4.1
  firebase_auth: ^3.8.0
  #firebase_core: ^1.19.1
  firebase_core: ^1.20.0
  # flutterfire_ui: ^0.4.2+2
  flutterfire_ui: 0.3.6+1
  google_sign_in: ^5.4.0
  sticky_grouped_list: ^3.1.0
  cached_network_image: ^3.2.1
  flutter_image: ^4.1.3
  persistent_bottom_nav_bar: ^4.0.2
  simple_grouped_listview: ^1.0.1
  auto_size_text: ^3.0.0
  top_snackbar_flutter: ^2.1.1
  logger: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  roundcheckbox: ^2.0.5
  shimmer: ^2.0.0
  font_awesome_flutter: ^10.1.0
  flutter_launcher_icons: ^0.10.0
  circle_checkbox: ^0.0.2+1
  flutter_login_facebook: 1.5.0+1
  cloud_firestore: ^3.4.6
  uni_links: ^0.5.1
  awesome_snackbar_content: ^0.0.8
  url_launcher: ^6.1.5
  flutter_share: ^2.0.0
  flutter_fadein: ^2.0.0

flutter_icons:
  image_path: "assets/images/shopping_list_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
