// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbbK_TxtzVTQLHybij8AOtMvmM4XrBHW4',
    appId: '1:1028524662787:web:3a0aa1674615c05b38ee36',
    messagingSenderId: '1028524662787',
    projectId: 'hot-deals-hungary',
    authDomain: 'hot-deals-hungary.firebaseapp.com',
    storageBucket: 'hot-deals-hungary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWryOJWmYdK0kJ6ARVwGkJhHLc_aWskes',
    appId: '1:1028524662787:android:decc0095ea5610f338ee36',
    messagingSenderId: '1028524662787',
    projectId: 'hot-deals-hungary',
    storageBucket: 'hot-deals-hungary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-CysIFZ6RnstFEQlQqPGl-J1xPhvppw',
    appId: '1:1028524662787:ios:23800d08d7cba0b038ee36',
    messagingSenderId: '1028524662787',
    projectId: 'hot-deals-hungary',
    storageBucket: 'hot-deals-hungary.appspot.com',
    iosClientId:
        '1028524662787-jft08l4pb568mpt4vp3g1m6l0a7ad6m8.apps.googleusercontent.com',
    iosBundleId: 'com.kebodev.szatyor',
  );
}
